### ISSUE TITLE
Support setting a additional text

### ISSUE THREAD

**Issue by kawpii** [max-wilkinson/copyrighter#1]
Thank you very much for the plugin, very useful.

I have a request, currently things look like this

```
/*
 *   Copyright (c) ${year} ${CompanyName}
 *   All rights reserved.
 */
```

instead also support adding some extra text with a setting option

ex:

```
/*
 *   Copyright (c) ${year} ${CompanyName}
 *   All rights reserved.
 *   ${extraNote}
 */
```
`"copyrighter.extraNote" : " extra note here"`

**Comment by max-wilkinson** [comment]
Great idea, thank you! I will work to get this integrated as soon as possible.

**Comment by kawpii** [comment]
Thanks for doing this!
